#!/bin/sh /etc/rc.common
#START=80

[ -f /etc/ath/wifi.conf ] && . /etc/ath/wifi.conf

boot() {
       wlan updateconf boot
       if [ "x$(/bin/config get factory_mode)" = "x1" ]; then
           /bin/sh /usr/sbin/factory-test.sh boot
       fi
       wlan down
       wlan up
       if [ "x$wig_exist" = "xon" ]; then
           wigig updateconf
           wigig down
           wigig up
       fi
       
       # disable wifi interface and and set power to amber
       # have been updated to /usr/sbin/factory-test.sh
}

start()    # don't use this command unless you know what it means
{
        wlan updateconf
        wlan up
}

stop()    # don't use this command unless you know what it means
{
        wlan updateconf
        wlan down
}

restart()
{
        wlan updateconf
        wlan down
        wlan up
}
