#!/bin/sh
export PATH=/bin:/sbin:/usr/bin:/usr/sbin

case "$ACTION" in
    RADARDETECT)
        [ -f /tmp/radardetect.pid ] || /usr/sbin/radardetect

        for chan in `echo $CHANNEL | sed 's/,/ /g'`; do 
            /usr/sbin/radardetect_cli -a $chan
        done
        echo "Radar Detected at ["`date` "] on channels [$CHANNEL]" >> /tmp/radardetect.log
        cp /tmp/radardetect.log /tmp/radardetect.log.tmp
        tail -c 1m /tmp/radardetect.log.tmp > /tmp/radardetect.log
        ;;
    BACKHAULSTA_CONNECT)
        echo "WIFI EVENT: $ACTION: $IFNAME is connected to AP" > /dev/console
        local lockfile="/tmp/.wsplcd.eventlock"
        local fileflag="/tmp/.wsplcd.lastrestart"
        local wifi_topology_file=`cat /etc/ath/wifi.conf  | grep WIFI_TOPOLOGY_FILE | awk -F= '{print $2}'`
        local ifname other_vap_connected
        [ -f $lockfile ] && return
        touch $lockfile
        for ifname in `awk -v input_optype=BACKHAUL -v input_opmode=STA -v output_rule=ifname -f /etc/search-wifi-interfaces.awk $wifi_topology_file`; do
            # Don't need to check this VAP's information
            [ "$ifname" = "$IFNAME" ] && continue
            other_vap_connected=`cat /proc/sys/net/$ifname/status | head -n 3 | grep RUN`
            [ -n "$other_vap_connected" ] && {
                break
            }
        done

        # If no other VAP connected, it means this VAP is first connected, just restart wsplcd directly.
        # If other VAP is connected, we don't know wsplcd has been restarted yet because of race condition.
        # - Two backhauls are connected at the same time.
        # Then, check last access time to determine need to restart wsplcd or not.
        if [ -n "$other_vap_connected" -a -f "$fileflag" ]; then
            a=`stat -t $fileflag | awk '{print $13}'`
            b=`date +%s`
            c=`expr $b - $a`
            [ "$c" -le 60 ] && {
                rm $lockfile
                return
            }
        fi
        touch "$fileflag"
        echo "WIFI EVENT: $ACTION: Restart wsplcd" > /dev/console
        ( sleep 2; /etc/init.d/wsplcd restart ) &
        rm $lockfile
        ;;
esac

